from __future__ import annotations
from typing import Any, Dict

class GameBase:
    key: str = "base"

    async def start(self, params: Dict[str, Any] | None = None) -> None: ...
    async def stop(self) -> None: ...
    async def on_button_pressed(self, btn_id: str) -> None: ...
    def status(self) -> Dict[str, Any]: ...
