from abc import ABC, abstractmethod

class GameMode(ABC):
    name: str = "BaseMode"

    @abstractmethod
    async def start(self): ...
    @abstractmethod
    async def handle_input(self, event): ...
    @abstractmethod
    async def tick(self): ...
    @abstractmethod
    async def stop(self): ...
    @abstractmethod
    def get_ui_state(self) -> dict: ...
