app:
  name: "the-mona"
  log_level: "INFO"

mqtt:
  host: "192.168.69.69" #"the-mona.local"
  port: 1883
  username: ""
  password: ""
  client_id: "the-mona-app"
  topic_prefix: "the-mona"
  qos_default: 1
  heartbeat_timeout_sec: 45

web:
  host: "0.0.0.0"
  port: 8080

audio:
  sink_preferred_name: "Analog"  # bijv. 3.5mm/USB DAC
  default_volume: 70

game:
  default_mode: "ReactionRace"
  tick_ms: 100
