- name: Configure hostapd
  become: true
  copy:
    dest: /etc/hostapd/hostapd.conf
    content: |
      interface=wlan0
      driver=nl80211
      ssid=The-Mona
      hw_mode=g
      channel=6
      macaddr_acl=0
      auth_algs=1
      ignore_broadcast_ssid=0
      wpa=2
      wpa_passphrase=mona1234
      wpa_key_mgmt=WPA-PSK
      rsn_pairwise=CCMP

- name: Enable and start hostapd
  become: true
  command: |
    systemctl unmask hostapd &&
    systemctl enable hostapd &&
    systemctl start hostapd

- name: Configure dnsmasq for DHCP and Captive Portal
  become: true
  copy:
    dest: /etc/dnsmasq.conf
    content: |
      interface=wlan0
      dhcp-range=192.168.69.2,192.168.69.69,255.255.255.0,24h
      address=/#/192.168.69.1
  notify: Restart dnsmasq

- name: Add DNS entry for the Flask app
  lineinfile:
    path: /etc/dnsmasq.conf
    line: "address=/the-mona-game/192.168.69.1"
    state: present
  notify: Restart dnsmasq

- name: Ensure override directory for dnsmasq exists
  become: true
  file:
    path: /etc/systemd/system/dnsmasq.service.d
    state: directory
    mode: '0755'

- name: Ensure override directory for hostapd exists
  become: true
  file:
    path: /etc/systemd/system/hostapd.service.d
    state: directory
    mode: '0755'

- name: Add persistent network dependency to dnsmasq
  become: true
  copy:
    dest: /etc/systemd/system/dnsmasq.service.d/override.conf
    content: |
      [Unit]
      After=network-online.target hostapd.service
      Wants=network-online.target

      [Service]
      ExecStartPre=/bin/sleep 5

- name: Add persistent network dependency to hostapd
  become: true
  copy:
    dest: /etc/systemd/system/hostapd.service.d/override.conf
    content: |
      [Unit]
      After=network-online.target
      Wants=network-online.target

- name: Reload systemd daemon
  become: true
  command: systemctl daemon-reload

- name: Enable dnsmasq and hostapd services
  become: true
  service:
    name: "{{ item }}"
    enabled: true
  loop:
    - hostapd
    - dnsmasq

- name: Restart dnsmasq and hostapd services
  become: true
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - hostapd
    - dnsmasq

- name: Disable power management for WiFi
  become: true
  copy:
    dest: /etc/udev/rules.d/70-wifi-powersave.rules
    content: |
      ACTION=="add", SUBSYSTEM=="net", KERNEL=="wlan0", RUN+="/sbin/iw dev wlan0 set power_save off"

- name: Clear old leases and config caches
  become: true
  shell: |
    rm -f /var/lib/misc/dnsmasq.leases
    rm -f /var/run/hostapd/wlan0
  ignore_errors: true

- name: Ensure nl80211 module is loaded at boot
  become: true
  lineinfile:
    path: /etc/modules
    line: nl80211
    state: present
