- name: Update package lists
  apt:
    update_cache: yes

- name: Install Mosquitto and Mosquitto clients
  apt:
    name:
      - mosquitto
      - mosquitto-clients
    state: present

- name: Enable and start Mosquitto service
  systemd:
    name: mosquitto
    enabled: yes
    state: started

- name: Configure Mosquitto to allow anonymous connections
  copy:
    dest: /etc/mosquitto/mosquitto.conf
    content: |
      listener 1883
      allow_anonymous true
  notify: Restart Mosquitto

- name: Configure static IP for wlan0
  copy:
    dest: /etc/dhcpcd.conf
    content: |
      interface wlan0
      static ip_address=192.168.69.69/24
      static routers=192.168.69.1
      static domain_name_servers=8.8.8.8 8.8.4.4
  notify: Restart Networking
