- name: Configure hostapd
  copy:
    dest: /etc/hostapd/hostapd.conf
    content: |
      interface=wlan0
      driver=nl80211
      ssid=The-Mona
      hw_mode=g
      channel=6
      macaddr_acl=0
      auth_algs=1
      ignore_broadcast_ssid=0
      wpa=2
      wpa_passphrase=mona1234
      wpa_key_mgmt=WPA-PSK
      rsn_pairwise=CCMP
  notify: Restart hostapd

- name: Configure dnsmasq
  copy:
    dest: /etc/dnsmasq.conf
    content: |
      interface=wlan0
      dhcp-range=192.168.69.100,192.168.69.250,255.255.255.0,24h
      address=/#/192.168.69.1
  notify: Restart dnsmasq

- name: Disable power management for WiFi
  copy:
    dest: /etc/udev/rules.d/70-wifi-powersave.rules
    content: |
      ACTION=="add", SUBSYSTEM=="net", KERNEL=="wlan0", RUN+="/sbin/iw dev wlan0 set power_save off"
